-- =====================================================
-- KOORA V1 — Migration Teams (création + seed + logos)
-- =====================================================
-- Migration autonome et idempotente : crée la table teams,
-- insère 131 équipes et pose les logos vérifiés.
-- Réexécutable sans erreur (on conflict do update).
--
-- Logos : repo GitHub luukhopman/football-logos (URLs testées HTTP 200).
--   → 80 équipes européennes ont un logo.
--   → Les autres (Amérique, Afrique, Asie) ont logo_url = NULL :
--     le composant TeamLogo affiche les initiales en fallback.

-- 1. Table
create table if not exists public.teams (
    id uuid primary key default gen_random_uuid(),
    name text not null unique,
    logo_url text,
    country text,
    league text,
    created_at timestamptz default now()
);

-- 2. Index (autocomplete + filtre par pays)
create index if not exists idx_teams_name on public.teams(name);
create index if not exists idx_teams_country on public.teams(country);

-- 3. Seed + logos (idempotent : met à jour si l'équipe existe déjà)
insert into public.teams (name, logo_url, country, league) values
('Paris Saint-Germain', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/France%20-%20Ligue%201/Paris%20Saint-Germain.png', 'France', 'Ligue 1'),
('Olympique de Marseille', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/France%20-%20Ligue%201/Olympique%20Marseille.png', 'France', 'Ligue 1'),
('Olympique Lyonnais', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/France%20-%20Ligue%201/Olympique%20Lyon.png', 'France', 'Ligue 1'),
('AS Monaco', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/France%20-%20Ligue%201/AS%20Monaco.png', 'France', 'Ligue 1'),
('LOSC Lille', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/France%20-%20Ligue%201/LOSC%20Lille.png', 'France', 'Ligue 1'),
('OGC Nice', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/France%20-%20Ligue%201/OGC%20Nice.png', 'France', 'Ligue 1'),
('Stade de Reims', null, 'France', 'Ligue 1'),
('FC Nantes', null, 'France', 'Ligue 1'),
('AS Saint-Étienne', null, 'France', 'Ligue 1'),
('Toulouse FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/France%20-%20Ligue%201/FC%20Toulouse.png', 'France', 'Ligue 1'),
('Real Madrid', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Real%20Madrid.png', 'Espagne', 'La Liga'),
('FC Barcelona', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/FC%20Barcelona.png', 'Espagne', 'La Liga'),
('Atlético Madrid', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Atl%C3%A9tico%20de%20Madrid.png', 'Espagne', 'La Liga'),
('Sevilla FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Sevilla%20FC.png', 'Espagne', 'La Liga'),
('Real Sociedad', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Real%20Sociedad.png', 'Espagne', 'La Liga'),
('Athletic Bilbao', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Athletic%20Bilbao.png', 'Espagne', 'La Liga'),
('Real Betis', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Real%20Betis%20Balompi%C3%A9.png', 'Espagne', 'La Liga'),
('Villarreal CF', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Villarreal%20CF.png', 'Espagne', 'La Liga'),
('Real Valladolid', null, 'Espagne', 'La Liga'),
('Rayo Vallecano', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Spain%20-%20LaLiga/Rayo%20Vallecano.png', 'Espagne', 'La Liga'),
('Juventus', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/Juventus%20FC.png', 'Italie', 'Serie A'),
('AC Milan', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/AC%20Milan.png', 'Italie', 'Serie A'),
('Inter Milan', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/Inter%20Milan.png', 'Italie', 'Serie A'),
('AS Roma', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/AS%20Roma.png', 'Italie', 'Serie A'),
('Napoli', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/SSC%20Napoli.png', 'Italie', 'Serie A'),
('Lazio', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/SS%20Lazio.png', 'Italie', 'Serie A'),
('Fiorentina', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/ACF%20Fiorentina.png', 'Italie', 'Serie A'),
('Atalanta', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/Atalanta%20BC.png', 'Italie', 'Serie A'),
('Torino FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/Torino%20FC.png', 'Italie', 'Serie A'),
('Bologna FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Italy%20-%20Serie%20A/Bologna%20FC%201909.png', 'Italie', 'Serie A'),
('Manchester United', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Manchester%20United.png', 'Angleterre', 'Premier League'),
('Manchester City', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Manchester%20City.png', 'Angleterre', 'Premier League'),
('Liverpool FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Liverpool%20FC.png', 'Angleterre', 'Premier League'),
('Arsenal FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Arsenal%20FC.png', 'Angleterre', 'Premier League'),
('Chelsea FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Chelsea%20FC.png', 'Angleterre', 'Premier League'),
('Tottenham Hotspur', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Tottenham%20Hotspur.png', 'Angleterre', 'Premier League'),
('Aston Villa', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Aston%20Villa.png', 'Angleterre', 'Premier League'),
('Brighton and Hove Albion', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Brighton%20%26%20Hove%20Albion.png', 'Angleterre', 'Premier League'),
('Newcastle United', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Newcastle%20United.png', 'Angleterre', 'Premier League'),
('Fulham FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Fulham%20FC.png', 'Angleterre', 'Premier League'),
('Brentford FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Brentford%20FC.png', 'Angleterre', 'Premier League'),
('Everton FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Everton%20FC.png', 'Angleterre', 'Premier League'),
('Leicester City', null, 'Angleterre', 'Premier League'),
('Leeds United', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/England%20-%20Premier%20League/Leeds%20United.png', 'Angleterre', 'Premier League'),
('Southampton FC', null, 'Angleterre', 'Premier League'),
('Bayern Munich', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/Bayern%20Munich.png', 'Allemagne', 'Bundesliga'),
('Borussia Dortmund', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/Borussia%20Dortmund.png', 'Allemagne', 'Bundesliga'),
('Bayer Leverkusen', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/Bayer%2004%20Leverkusen.png', 'Allemagne', 'Bundesliga'),
('RB Leipzig', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/RB%20Leipzig.png', 'Allemagne', 'Bundesliga'),
('Borussia Mönchengladbach', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/Borussia%20M%C3%B6nchengladbach.png', 'Allemagne', 'Bundesliga'),
('VfB Stuttgart', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/VfB%20Stuttgart.png', 'Allemagne', 'Bundesliga'),
('SC Freiburg', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/SC%20Freiburg.png', 'Allemagne', 'Bundesliga'),
('Eintracht Frankfurt', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/Eintracht%20Frankfurt.png', 'Allemagne', 'Bundesliga'),
('VfL Wolfsburg', null, 'Allemagne', 'Bundesliga'),
('Schalke 04', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Germany%20-%20Bundesliga/FC%20Schalke%2004.png', 'Allemagne', 'Bundesliga'),
('Ajax Amsterdam', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Netherlands%20-%20Eredivisie/Ajax%20Amsterdam.png', 'Pays-Bas', 'Eredivisie'),
('PSV Eindhoven', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Netherlands%20-%20Eredivisie/PSV%20Eindhoven.png', 'Pays-Bas', 'Eredivisie'),
('Feyenoord', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Netherlands%20-%20Eredivisie/Feyenoord%20Rotterdam.png', 'Pays-Bas', 'Eredivisie'),
('AZ Alkmaar', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Netherlands%20-%20Eredivisie/AZ%20Alkmaar.png', 'Pays-Bas', 'Eredivisie'),
('Vitesse', null, 'Pays-Bas', 'Eredivisie'),
('FC Utrecht', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Netherlands%20-%20Eredivisie/FC%20Utrecht.png', 'Pays-Bas', 'Eredivisie'),
('FC Groningen', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Netherlands%20-%20Eredivisie/FC%20Groningen.png', 'Pays-Bas', 'Eredivisie'),
('SC Heerenveen', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Netherlands%20-%20Eredivisie/SC%20Heerenveen.png', 'Pays-Bas', 'Eredivisie'),
('Galatasaray', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/T%C3%BCrkiye%20-%20S%C3%BCper%20Lig/Galatasaray.png', 'Turquie', 'Super Lig'),
('Fenerbahçe', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/T%C3%BCrkiye%20-%20S%C3%BCper%20Lig/Fenerbahce.png', 'Turquie', 'Super Lig'),
('LA Galaxy', null, 'USA', 'MLS'),
('New York City FC', null, 'USA', 'MLS'),
('Los Angeles FC', null, 'USA', 'MLS'),
('Seattle Sounders', null, 'USA', 'MLS'),
('FC Dallas', null, 'USA', 'MLS'),
('Houston Dynamo', null, 'USA', 'MLS'),
('Portland Timbers', null, 'USA', 'MLS'),
('Toronto FC', null, 'Canada', 'MLS'),
('Vancouver Whitecaps', null, 'Canada', 'MLS'),
('Colorado Rapids', null, 'USA', 'MLS'),
('Club América', null, 'Mexique', 'Liga MX'),
('UNAM Pumas', null, 'Mexique', 'Liga MX'),
('Cruz Azul', null, 'Mexique', 'Liga MX'),
('Guadalajara', null, 'Mexique', 'Liga MX'),
('Flamengo', null, 'Brésil', 'Série A'),
('São Paulo FC', null, 'Brésil', 'Série A'),
('Corinthians', null, 'Brésil', 'Série A'),
('Palmeiras', null, 'Brésil', 'Série A'),
('Cruzeiro', null, 'Brésil', 'Série A'),
('Botafogo', null, 'Brésil', 'Série A'),
('Atlético Mineiro', null, 'Brésil', 'Série A'),
('Santos FC', null, 'Brésil', 'Série A'),
('Grêmio', null, 'Brésil', 'Série A'),
('Internacional', null, 'Brésil', 'Série A'),
('Boca Juniors', null, 'Argentine', 'Superliga'),
('River Plate', null, 'Argentine', 'Superliga'),
('San Lorenzo', null, 'Argentine', 'Superliga'),
('Independiente', null, 'Argentine', 'Superliga'),
('Racing Club', null, 'Argentine', 'Superliga'),
('Vélez Sársfield', null, 'Argentine', 'Superliga'),
('Al Ahly', null, 'Égypte', 'Premier League'),
('Zamalek', null, 'Égypte', 'Premier League'),
('Kaizer Chiefs', null, 'Afrique du Sud', 'PSL'),
('Orlando Pirates', null, 'Afrique du Sud', 'PSL'),
('Al-Hilal', null, 'Arabie Saoudite', 'SPL'),
('Al-Nassr', null, 'Arabie Saoudite', 'SPL'),
('Suwon FC', null, 'Corée du Sud', 'K League'),
('FC Seoul', null, 'Corée du Sud', 'K League'),
('Shanghai SIPG', null, 'Chine', 'Chinese Super League'),
('Beijing Guoan', null, 'Chine', 'Chinese Super League'),
('Glasgow Rangers', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Scotland%20-%20Scottish%20Premiership/Rangers%20FC.png', 'Écosse', 'Premiership'),
('Glasgow Celtic', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Scotland%20-%20Scottish%20Premiership/Celtic%20FC.png', 'Écosse', 'Premiership'),
('Heart of Midlothian', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Scotland%20-%20Scottish%20Premiership/Heart%20of%20Midlothian%20FC.png', 'Écosse', 'Premiership'),
('Hibernian FC', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Scotland%20-%20Scottish%20Premiership/Hibernian%20FC.png', 'Écosse', 'Premiership'),
('SL Benfica', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Portugal%20-%20Liga%20Portugal/SL%20Benfica.png', 'Portugal', 'Primeira Liga'),
('Sporting CP', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Portugal%20-%20Liga%20Portugal/Sporting%20CP.png', 'Portugal', 'Primeira Liga'),
('FC Porto', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Portugal%20-%20Liga%20Portugal/FC%20Porto.png', 'Portugal', 'Primeira Liga'),
('SC Braga', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Portugal%20-%20Liga%20Portugal/SC%20Braga.png', 'Portugal', 'Primeira Liga'),
('Anderlecht', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Belgium%20-%20Jupiler%20Pro%20League/RSC%20Anderlecht.png', 'Belgique', 'Pro League'),
('Club Brugge', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Belgium%20-%20Jupiler%20Pro%20League/Club%20Brugge%20KV.png', 'Belgique', 'Pro League'),
('RSC Charleroi', null, 'Belgique', 'Pro League'),
('FC Basel', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Switzerland%20-%20Super%20League/FC%20Basel%201893.png', 'Suisse', 'Super League'),
('FC Zurich', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Switzerland%20-%20Super%20League/FC%20Z%C3%BCrich.png', 'Suisse', 'Super League'),
('BSC Young Boys', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Switzerland%20-%20Super%20League/BSC%20Young%20Boys.png', 'Suisse', 'Super League'),
('FC Red Bull Salzburg', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Austria%20-%20Bundesliga/Red%20Bull%20Salzburg.png', 'Autriche', 'Bundesliga'),
('SK Rapid Wien', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Austria%20-%20Bundesliga/Rapid%20Vienna.png', 'Autriche', 'Bundesliga'),
('Legia Warsaw', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Poland%20-%20PKO%20BP%20Ekstraklasa/Legia%20Warszawa.png', 'Pologne', 'Ekstraklasa'),
('Wisła Kraków', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Poland%20-%20PKO%20BP%20Ekstraklasa/Wisla%20Krak%C3%B3w.png', 'Pologne', 'Ekstraklasa'),
('Dynamo Kyiv', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Ukraine%20-%20Premier%20Liga/Dynamo%20Kyiv.png', 'Ukraine', 'Premier League'),
('Shakhtar Donetsk', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Ukraine%20-%20Premier%20Liga/Shakhtar%20Donetsk.png', 'Ukraine', 'Premier League'),
('FCSB', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Romania%20-%20SuperLiga/FCSB.png', 'Roumanie', 'Liga I'),
('CFR Cluj', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Romania%20-%20SuperLiga/CFR%20Cluj.png', 'Roumanie', 'Liga I'),
('Slavia Prague', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Czech%20Republic%20-%20Chance%20Liga/SK%20Slavia%20Prague.png', 'Tchéquie', 'Liga'),
('AC Sparta Praha', 'https://raw.githubusercontent.com/luukhopman/football-logos/master/logos/Czech%20Republic%20-%20Chance%20Liga/AC%20Sparta%20Prague.png', 'Tchéquie', 'Liga'),
('Tokyo Verdy', null, 'Japon', 'J-League'),
('Urawa Red Diamonds', null, 'Japon', 'J-League')
on conflict (name) do update
  set logo_url = excluded.logo_url,
      country  = excluded.country,
      league   = excluded.league;

-- 4. Vérifications
select count(*) as total_teams from public.teams;
select count(*) as teams_with_logo from public.teams where logo_url is not null;
select name, country, league from public.teams where logo_url is null order by country, name;